### ISSUE TITLE
use greenkeeper bot

### ISSUE THREAD

**Issue by Holger-Will** [kaskadi/template-action#2]
use the [greenkeeper](https://greenkeeper.io/ ) bot for automated dependency management when using npm.

**Comment by alexlemaire** [comment]
[greenkeeper](https://greenkeeper.io/) has now stopped its service. They moved onto [Snyk](https://snyk.io/) (they helped them develop their dependency management module) and so I granted access to `Snyk` for `kaskadi`.

It should:
- check on new PRs for any vulnerabilities we may introduce
- open PRs for patching dependencies which introduce known vulnerabilities
- open PRS to update outdated dependencies

`Snyk` scans monitored repos on daily basis by default. We can reduce the frequency to a weekly scan also.

`Snyk` is free for any public repos & the free plan has a limit of 200 scans per month for private repos

Tomorrow I'll take care of implementing auto-monitoring for new repos (and also document how to enable monitoring manually)

Closing this for now!
